server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: admin
    password: 0852

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      show-sql: true