server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: admin
    password: 0852

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        format_sql: true
    show_sql: true
    hibernate:
      ddl-auto: update